### ISSUE TITLE
Downloading slows down

### ISSUE THREAD

**Issue by matlink** [NoMore201/googleplay-api#35] opened 2018-01-19 08:31 UTC
Related to https://github.com/matlink/gplaycli/issues/156
In fact, we should find a way to yield chunks of data instead of returning the whole binary data. I found that CPU is at 100% when downloading, which is, I think, due to the memory reallocation of the string.

For now, I have 2 ways to achieve that:
- yielding chunks in `_deliver_data()` and in `delivery()`
- passing a filename argument to `delivery()` to directly write down the response

The first one appears to be the most elegant way to me, but it requires more changes in the code.
What do you think?

**Comment by NoMore201** [comment] 2018-01-22 12:11
https://stackoverflow.com/questions/16694907/how-to-download-large-file-in-python-with-requests-py
Does `stream=True` achieve the same result? If it does, the we need to add it to `_delivery_data` when `progress_bar == False`.
https://github.com/NoMore201/googleplay-api/blob/5013dbe5ab73c45ebdeabaae55d3c327e94235c0/gpapi/googleplay.py#L487-L498

**Comment by NoMore201** [comment] 2018-01-26 16:47
I think I have found a solution for this. Basically requests `iter_content(chunksize)` will return a generator, which can be iterated to get chunk of bytes with a simple for, like in current code:
https://github.com/NoMore201/googleplay-api/blob/e1c73c8af06ae877cb4df35f83cafc8cb6d51171/gpapi/googleplay.py#L495-L501
The problem is that I can't iterate this generator in gpapi, because it will of course parse all the file into memory and assign it to the result dictionary. The solution would be to return directly the generator, and let users iterate over it and provide a progress bar
```python
def _deliver_data(self, url, cookies, progress_bar):
        headers = self.getDefaultHeaders()
        response = requests.get(url, headers=headers,
                                cookies=cookies, verify=ssl_verify,
                                stream=True, timeout=60,
                                proxies=self.proxies_config)
        return response.iter_content(chunk_size=(32 * 1 << 10))
```
So users will have to iterate
```python
response = gpapi_instance.download("com.example.apk", versionCode=None, expansion_files=True)
response_gen = response.get('data')
for chunk in response_gen:
    apk_file.write(chunk)
    # display progress bar
```

I'm trying it right now and it works well, no memory or speed problems. Let me know if this approach makes sense

**Comment by matlink** [comment] 2018-01-26 17:01
It totally makes sense.
Tell me when you push it to github, I'll adapt my code.

**Comment by NoMore201** [comment] 2018-01-26 17:34
Commit is live, I'll push a new version as soon as I finish updating all device properties from play-store-api. I will notify here when the process is complete.

**Comment by NoMore201** [comment] 2018-01-27 18:04
I'm about to push version 0.4 here and on pypi.

**Closed by NoMore201** 2018-01-27 18:04 UTC
